title : Algorithm Aggregator
description: The Algorithm Aggregator project is a attempt to create a cluster of usefull algorithms which are preimplemented in popular programming language.
theme: jekyll-theme-merlot
